# Generated by Django 5.2.4 on 2025-07-11 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='home_location',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='office_location',
            new_name='office_address',
        ),
    ]
