# Generated by Django 5.2.4 on 2025-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orbit', '0003_alter_customuser_managers_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='documents',
            field=models.FileField(blank=True, help_text='Upload PDF or image files only', null=True, upload_to='user_documents/'),
        ),
    ]
